name: last_fm_api
description: LastFM API bindings for Dart
version: 0.0.1
homepage: https://github.com/lututui/dart-lastfm-api-bindings

publish_to: 'none'

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: ^0.12.1
  meta: ^1.1.8
  crypto: ^2.1.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
